### ISSUE TITLE
Feature request: background color instead of divider

### ISSUE THREAD

**Issue by bartdeijkers** [bartdeijkers/selligent-modular-email-template#1]
In order to create uniform sections it should be possible to hide the divider line and replace it with spacing with the background color of the block.

**Comment by fransyozef** [comment]
Or just use CUSTOM_DIVIDER .. When CUSTOM_DIVIDER is used, the normal divider is overridden and the content of CUSTOM_DIVIDER is used.

**Comment by bartdeijkers** [comment]
Ok! This ticket can be closed.
