### ISSUE TITLE
Core article database columns not up to date

### ISSUE THREAD

**Issue by lindabemelmans** [bartdeijkers/selligent-modular-email-template#12]
Core article database columns is not correct corresponding to the script.

**Comment by lindabemelmans** [comment]
another thing:

SUBTITLE_CSS
Text
100
List_singlesel

is just single line i assume.

----
Default sensors - waarom zijn er enkele  ITEM.LINK_URL doorgestreept zoals: 
101 Hyperlink Url ITEM.LINK_URL

**Comment by fransyozef** [comment]
"Core article database columns is not correct corresponding to the script."

Yes it needs to be updated

But feel free to update @lindabemelmans

**Comment by fransyozef** [comment]
"SUBTITLE_CSS
Text
100
List_singlesel

is just single line i assume."

No .. if it's a single single line, you cannot predefined multiple styles.

**Comment by fransyozef** [comment]
"Default sensors - waarom zijn er enkele ITEM.LINK_URL doorgestreept zoals:
101 Hyperlink Url ITEM.LINK_URL"

That's just Github markup messing things up.

**Comment by bartdeijkers** [comment]
Documentation is updated. Issue is hereby resolved.
