### ISSUE TITLE
dubble style 

### ISSUE THREAD

**Issue by lindabemelmans** [bartdeijkers/selligent-modular-email-template#13]
<div contenteditable="FALSE" id="MACONTAINER" maconstraint="" mahidediv="TRUE" maparameter="ARTICLES\MAIN">

         <div contenteditable="TRUE" id="MAITEM" MACLASS="admin_row">

           <div STYLE="font-size:13px;border-bottom: 1px solid #~IF(CHKPROP(ITEM.OPTIONS,'HIDE_DIVIDER')=1,fff,999)~" class="admin_row_wrapper" style="display:block">

-----------
-->>   *style="display:block*">

**Comment by fransyozef** [comment]
opgelost in 

https://github.com/Seapher/selligent-modular-email-template/commit/462cc492e6f7af5a0dd76a3db1dbe57bf0c43361
