### ISSUE TITLE
Border around article block

### ISSUE THREAD

**Issue by lindabemelmans** [bartdeijkers/selligent-modular-email-template#9]
I would like to have the option to put a border around an article blok.

**Comment by fransyozef** [comment]
There is an option to add border in the article (border_color)

**Comment by bartdeijkers** [comment]
value for border_color is the standard hex color code without # right?

**Comment by fransyozef** [comment]
correct .. all the _color fields are WITHOUT # 

If you use custom css for example TITLE_CSS .. then you can use color:#
